// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Text.RegularExpressions;

namespace Aspire.Hosting.Radius.Secrets;

/// <summary>
/// Minimal reader for a committed, encrypted Bitnami <c>SealedSecret</c> manifest. Extracts
/// the <c>metadata.name</c> / <c>metadata.namespace</c> that identify the <c>Secret</c> the
/// controller will materialize (used for the <c>secretStores.resource</c> reference and the
/// deploy-time materialization poll). The manifest content is already encrypted; only its
/// metadata is read. A missing or unreadable manifest fails with <c>ASPIRERADIUS044</c>.
/// </summary>
internal static class SealedSecretManifest
{
    /// <summary>
    /// Reads the <c>metadata.name</c> (required) and <c>metadata.namespace</c> (optional,
    /// defaulting to <paramref name="defaultNamespace"/>) from the manifest at
    /// <paramref name="manifestPath"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// The manifest is missing, unreadable, or has no <c>metadata.name</c>
    /// (<c>ASPIRERADIUS044</c>).
    /// </exception>
    internal static (string Namespace, string Name) ReadMetadata(
        string storeName, string manifestPath, string defaultNamespace)
    {
        string text;
        try
        {
            text = File.ReadAllText(manifestPath);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or NotSupportedException)
        {
            throw new InvalidOperationException(
                $"Secret store '{storeName}' references a SealedSecret manifest at '{manifestPath}' that " +
                $"is missing or unreadable ({ex.GetType().Name}). Diagnostic: ASPIRERADIUS044.", ex);
        }

        var name = MatchMetadataField(text, "name");
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new InvalidOperationException(
                $"Secret store '{storeName}' references a SealedSecret manifest at '{manifestPath}' that has " +
                "no metadata.name. Diagnostic: ASPIRERADIUS044.");
        }

        var ns = MatchMetadataField(text, "namespace");
        return (string.IsNullOrWhiteSpace(ns) ? defaultNamespace : ns!, name!);
    }

    // Matches a top-level metadata field (name/namespace) at two-space indentation under
    // `metadata:`. SealedSecret manifests are small and machine-generated by kubeseal, so a
    // line-oriented match is sufficient without taking a YAML dependency.
    private static string? MatchMetadataField(string text, string field)
    {
        var match = Regex.Match(
            text,
            $@"(?m)^\s{{2,}}{Regex.Escape(field)}:\s*(?<v>[^\s#]+)\s*$");
        return match.Success ? match.Groups["v"].Value.Trim('\'', '"') : null;
    }
}
