// Licensed to the .NET Foundation under one or more agreements.
// The .NET Foundation licenses this file to you under the MIT license.

using System.Text.RegularExpressions;

namespace Aspire.Hosting.Radius.Secrets;

/// <summary>
/// Minimal reader for a committed, encrypted Bitnami <c>SealedSecret</c> manifest. Extracts
/// the <c>metadata.name</c> / <c>metadata.namespace</c> that identify the <c>Secret</c> the
/// controller will materialize (used for the <c>secretStores.resource</c> reference and the
/// deploy-time materialization poll). The manifest content is already encrypted; only its
/// metadata is read. A missing or unreadable manifest fails with <c>ASPIRERADIUS044</c>.
/// </summary>
internal static class SealedSecretManifest
{
    /// <summary>
    /// The result of reading a <c>SealedSecret</c> manifest's identifying metadata.
    /// <see cref="NamespaceWasExplicit"/> distinguishes a namespace read from the manifest from
    /// one defaulted to the owning environment: only when defaulted may the deploy step add
    /// <c>-n</c> to <c>kubectl apply</c> (passing <c>-n</c> when the object already declares a
    /// different namespace makes <c>kubectl apply</c> fail).
    /// </summary>
    internal readonly record struct Metadata(string Namespace, string Name, bool NamespaceWasExplicit);

    /// <summary>
    /// Reads the <c>metadata.name</c> (required) and <c>metadata.namespace</c> (optional,
    /// defaulting to <paramref name="defaultNamespace"/>) from the manifest at
    /// <paramref name="manifestPath"/>.
    /// </summary>
    /// <exception cref="InvalidOperationException">
    /// The manifest is missing, unreadable, or has no <c>metadata.name</c>
    /// (<c>ASPIRERADIUS044</c>).
    /// </exception>
    internal static Metadata ReadMetadata(
        string storeName, string manifestPath, string defaultNamespace)
    {
        string text;
        try
        {
            text = File.ReadAllText(manifestPath);
        }
        catch (Exception ex) when (ex is IOException or UnauthorizedAccessException or NotSupportedException)
        {
            throw new InvalidOperationException(
                $"Secret store '{storeName}' references a SealedSecret manifest at '{manifestPath}' that " +
                $"is missing or unreadable ({ex.GetType().Name}). Diagnostic: ASPIRERADIUS044.", ex);
        }

        // Restrict the metadata search to the top-level `metadata:` block so we never pick up a
        // nested `spec.template.metadata.name/namespace` or an `encryptedData` key literally named
        // `name`/`namespace`. kubeseal output looks like:
        //   apiVersion: bitnami.com/v1alpha1
        //   kind: SealedSecret
        //   metadata:
        //     name: db-creds
        //     namespace: app
        //   spec:
        //     encryptedData:
        //       username: AgB...
        //     template:
        //       metadata:
        //         name: db-creds        <-- must NOT be matched
        var metadataBlock = ExtractTopLevelMetadataBlock(text);

        var name = MatchMetadataField(metadataBlock, "name");
        if (string.IsNullOrWhiteSpace(name))
        {
            throw new InvalidOperationException(
                $"Secret store '{storeName}' references a SealedSecret manifest at '{manifestPath}' that has " +
                "no metadata.name. Diagnostic: ASPIRERADIUS044.");
        }

        var ns = MatchMetadataField(metadataBlock, "namespace");
        var namespaceWasExplicit = !string.IsNullOrWhiteSpace(ns);
        return new Metadata(namespaceWasExplicit ? ns! : defaultNamespace, name!, namespaceWasExplicit);
    }

    // Returns the region of the document that belongs to the top-level `metadata:` mapping: the
    // lines after a column-0 `metadata:` up to (but not including) the next column-0 key. Falls
    // back to the whole document when no top-level `metadata:` is found (the field match below
    // then simply finds nothing and callers report ASPIRERADIUS044).
    private static string ExtractTopLevelMetadataBlock(string text)
    {
        // Match `metadata:` anchored at column 0 (no leading whitespace), then capture every
        // subsequent line that is either blank or indented (i.e. still inside the mapping),
        // stopping at the next non-indented key such as `spec:`.
        var match = Regex.Match(text, @"(?m)^metadata:[ \t]*\r?$(?<body>(\r?\n([ \t]+\S.*|[ \t]*))*)");
        return match.Success ? match.Groups["body"].Value : text;
    }

    // Matches a metadata field (name/namespace) at any indentation within the already-narrowed
    // top-level `metadata:` block. The block is small and machine-generated by kubeseal, so a
    // line-oriented match is sufficient without taking a YAML dependency.
    private static string? MatchMetadataField(string metadataBlock, string field)
    {
        var match = Regex.Match(
            metadataBlock,
            $@"(?m)^\s+{Regex.Escape(field)}:\s*(?<v>[^\s#]+)\s*$");
        return match.Success ? match.Groups["v"].Value.Trim('\'', '"') : null;
    }
}
