<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>a1f3c2d7-9e5b-4082-bde1-60f47a83c915</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <AspireProjectOrPackageReference Include="Aspire.Hosting.AppHost" />
    <AspireProjectOrPackageReference Include="Aspire.Hosting.Radius" />
  </ItemGroup>

</Project>
