<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>$(DefaultTargetFramework)</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <IsAspireHost>true</IsAspireHost>
    <UserSecretsId>b66c10be-ac7d-4f22-ae67-6913aec295ac</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <AspireProjectOrPackageReference Include="Aspire.Hosting.AppHost" />
    <AspireProjectOrPackageReference Include="Aspire.Hosting.Radius" />
    <AspireProjectOrPackageReference Include="Aspire.Hosting.Redis" />
  </ItemGroup>

</Project>
